server:
  port: 8082

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/powerup
#    username: root
#    password: root
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}

logging:
  level:
    org:
      springframework:
        security: TRACE
        web: DEBUG


appDescription: "Pragma Powerup"
appVersion: "1.0.0"
